### ISSUE TITLE
Problem connect to CRM

### ISSUE THREAD

**Issue by celia-ms** [DynamicsCRM/crm-mobilesdk-library-for-android#1]
Hello,
I'm starting with Microsoft Dynamics and I'm trying to ingregate a mobile application with Microsoft Dynamics CRM 2015 using the new Microsoft Dynamics CRM Mobile SDK for Android and I have problems making some requests: I can't access to the information of my CRM. I authenticate succesfully by means of SOAP (http://jlattimer.blogspot.com.es/2015/02/soap-only-authentication-using-java.html) instead of OAuth, I also generate CRM classes with the MobileSDKGen tool but I don't know how to make a correct request in order to get the information about my CRM. What data should I send in the message's header?
The class builder of OrganizationServiceProxy allows 2 parameters:
- OrganizationServiceProxy(URI, SessionToken)
- OrganizationServiceProxy(URI, RequestInterceptor)

On one hand, using SOAP authentication, the server returns a response message that contains not only one but three session tokens: securityToken0, securityToken1  and keyIdentifier.
On the other hand, I don't understand how to create a RequestInterceptor as I have never used before Retrofit library. 

Could anyone help me? How can I make a request to CRM server with Mobile SDK, using SOAP authentication?

Thank you very much

**Comment by phecke** [comment]
Hello;

In past SDK releases we did provide a Java sample that was able to access CRM, so it is possible. However, our SDK team did not have the resources to support such a scenario and we pulled the code from all recent CRM SDK releases. Today, there are two recommended methods to authenticate with CRM using Java code and access the web services. The first is to use the crm-mobilesdk-library-for-android that we provide on GitHub. That download contains library code for OAuth authentication, plus a full set of SOAP and OData classes for sending requests to the server and receiving responses.

The second method is to use the new Web API (currently available for CRM Online only). While the Web API is currently in preview, it will go RTM in the next major CRM release coming soon. The Web API is our future recommended method for cross-platform web access to Dynamics CRM. We have Java sample code in development that demonstrates the Web API that will be published later this year.

Today, if you want to write Java code to access an on-premises Dynamics CRM, I would recommend you look at the crm-mobilesdk-library-for-android.

If you already have acquired the authentication access token, you would set the Authorize header of the HTTP request to the word “Bearer” + <access token> and then populate the message request body with the SOAP information. Again, refer to the request and response SOAP classes in the Mobile SDK.

Thanks

Peter Hecke / Senior Programming Writer / Microsoft Dynamics CRM SDK team

**Comment by w9jds** [comment]
If you want to make a RequestInterceptor you should make it like this:

```
    requestInterceptor = new RequestInterceptor() {
        @Override
        public void intercept(RequestFacade request) {
            request.addHeader("Authorization", "Bearer " + currentSessionToken);
        }
    };
```

However, doing this is basically the same as passing in the SessionToken. It was just added to make it so you don't have to store both a header and the token. So Retrofit isn't actually required to use the SDK (I even removed the callback use for all of the requests so you don't have to even touch Retrofit if you don't want to).

**Comment by w9jds** [comment]
This was completely changed in the latest build. I have removed everything except for just one constructor. You now just need the endpoint url and the session token. You should be building the application around a singleton structure for the org services so you should only have one of each instance making this an extremely easy to use system.
