### ISSUE TITLE
get appointment startdate always give "JAN" month

### ISSUE THREAD

**Issue by patelanil2007** [DynamicsCRM/crm-mobilesdk-library-for-android#13]
@w9jds @CarlosMendonca @saldana  @JimDaly @msftgits 

 i solve this issue just add below code in Utils.java

`SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'");
                    simpleDateFormat.setTimeZone(TimeZone.getTimeZone("GMT"));` 

Instead of

`SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-DD'T'HH:mm:ss'Z'");`

**Comment by w9jds** [comment]
This has already been addressed inside of the open pull request. A sizable update is coming to the SDK and this fix will be included.

**Comment by patelanil2007** [comment]
till get wrong time. how to solve this issue?
date issue solve by above code but time got wrong.

@w9jds

**Comment by w9jds** [comment]
@patelanil2007 you need to use: 

`SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");`
