### ISSUE TITLE
Issue with create request

### ISSUE THREAD

**Issue by earnshae** [DynamicsCRM/crm-mobilesdk-library-for-android#3]
Hi I have been using your library to access and pull data from Microsoft Dynamics successfully, recently I have been trying to create records in the CRM with the library and have been getting an error as a response to the create the error body is 

`<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Body>
        <s:Fault>
            <faultcode xmlns:a="http://schemas.microsoft.com/net/2005/12/windowscommunicationfoundation/dispatcher">a:DeserializationFailed</faultcode>
            <faultstring xml:lang="en-US">
            The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:entity. The InnerException message was 'Error in line 1 position 882. Expecting state 'Element'.. Encountered 'Text'  with name '', namespace ''. '.  Please see InnerException for more details.
            </faultstring>
        </s:Fault>
    </s:Body>
</s:Envelope>
`

Here is the code used to generate the error.

orgService = new OrganizationServiceProxy(Constant.ENDPOINT, CRMLogin.getRequestInterceptor());

```

Entity workOrder = new Entity("x_workorder");

final String activityid = service_appointment.getValue(SAptEntry.ACTIVITY_ID);

Log.d("pushUpdatesToCRM>>>","Creating WorkOrder for Activity: "+activityid);

orgService.Create(workOrder, new Callback<UUID>() {

        @Override
        public void success(UUID uuid, Response response) {
            Log.d("pushUpdateToCRM>>>", "WorkOrder created for Activity:" + activityid);
        }

        @Override
        public void failure(RetrofitError error) {
            Log.d("pushUpdateToCRM>>>", "WorkOrder not created for Activity: " + activityid);
            Log.d("pushUpdateToCRM>>>", "WorkOrder create error: " + error.getMessage());
            Log.d("UGG", error.getBody().toString());
        }
    });
```

Do you have any suggestions on how to proceed? Thanks.

**Comment by earnshae** [comment]
Okay I solved this this was a problem with the library I can submit the code if you would like.

**Comment by phecke** [comment]
Yes, please.

**Comment by earnshae** [comment]
The problem was that the payload to the create request was a mixture of escaped and unescaped xml.

I added this function to The Utils Library:

```
    public static String decodeXML(String data) {
        return data
                .replace("&amp;", "&")
                .replace("&lt;", "<")
                .replace("&gt;", ">")
                .replace("&quot;", "\"")
                .replace("&apos;", "'");
    }
```

and altered the create statement in Organization Service Proxy to read:

`content.append(Utils.decode(Utils.objectToXml(entity, "d:entity", false)))`;

I am sure that you are probably more familiar with the library and could fix the objectToXML for this case better. But that got it posting

**Comment by w9jds** [comment]
With the huge new merge of changes this was fixed.
