### ISSUE TITLE
where to register android app in crm?

### ISSUE THREAD

**Issue by patelanil2007** [DynamicsCRM/crm-mobilesdk-library-for-android#5]
give me web link where i can register my android app and get CLIENT_ID and REDIRECT_URI

**Comment by phecke** [comment]
If you are using a CRM Online organization:
https://msdn.microsoft.com/en-us/library/mt622431.aspx

If you are using CRM IFD: https://msdn.microsoft.com/en-us/library/dn531010.aspx
